namespace CartonCaps.Model
{
    /// <summary>
    /// Represents a referral code generated by a user.
    /// </summary>
    public class Referral
    {
        /// <summary>
        /// Public referral id.
        /// </summary>
        public int ReferralId { get; set; } = default!;
        /// <summary>
        /// Public referral code shared with new users.
        /// </summary>
        public string Code { get; set; } = default!;

        /// <summary>
        /// User who generated the referral.
        /// </summary>
        public string UserId { get; set; } = default!;

        /// <summary>
        /// pending | redeemed | expired
        /// </summary>
        public string Status { get; set; } = default!;

        public DateTime Expiration { get; set; }

        public DateTime? RedeemDate { get; set; }

        /// <summary>
        /// User who redeemed the referral (if any).
        /// </summary>
        public string? ReferredUserId { get; set; }
    }
}
